# Используем официальный образ Node.js
FROM node:20

# Устанавливаем рабочую директорию внутри контейнера
WORKDIR /src

# Копируем package.json и package-lock.json в рабочую директорию
COPY package*.json ./ 

# Устанавливаем зависимости
RUN npm install

# Копируем исходные файлы проекта
COPY . .

# Открываем порт 3000 для NestJS
EXPOSE 3000

# Команда для запуска приложения
CMD ["npm", "run", "start:dev"]
